module.BundlaContainer NoClassDefFoundError catch and changed to ClassNotFound exception, now it should be properly catch by the rest of the application  #247